require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe CreateUserFavoritesController, :type => :controller do

  # This should return the minimal set of attributes required to create a valid
  # CreateUserFavorite. As you add validations to CreateUserFavorite, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # CreateUserFavoritesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all create_user_favorites as @create_user_favorites" do
      create_user_favorite = CreateUserFavorite.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:create_user_favorites)).to eq([create_user_favorite])
    end
  end

  describe "GET show" do
    it "assigns the requested create_user_favorite as @create_user_favorite" do
      create_user_favorite = CreateUserFavorite.create! valid_attributes
      get :show, {:id => create_user_favorite.to_param}, valid_session
      expect(assigns(:create_user_favorite)).to eq(create_user_favorite)
    end
  end

  describe "GET new" do
    it "assigns a new create_user_favorite as @create_user_favorite" do
      get :new, {}, valid_session
      expect(assigns(:create_user_favorite)).to be_a_new(CreateUserFavorite)
    end
  end

  describe "GET edit" do
    it "assigns the requested create_user_favorite as @create_user_favorite" do
      create_user_favorite = CreateUserFavorite.create! valid_attributes
      get :edit, {:id => create_user_favorite.to_param}, valid_session
      expect(assigns(:create_user_favorite)).to eq(create_user_favorite)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new CreateUserFavorite" do
        expect {
          post :create, {:create_user_favorite => valid_attributes}, valid_session
        }.to change(CreateUserFavorite, :count).by(1)
      end

      it "assigns a newly created create_user_favorite as @create_user_favorite" do
        post :create, {:create_user_favorite => valid_attributes}, valid_session
        expect(assigns(:create_user_favorite)).to be_a(CreateUserFavorite)
        expect(assigns(:create_user_favorite)).to be_persisted
      end

      it "redirects to the created create_user_favorite" do
        post :create, {:create_user_favorite => valid_attributes}, valid_session
        expect(response).to redirect_to(CreateUserFavorite.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved create_user_favorite as @create_user_favorite" do
        post :create, {:create_user_favorite => invalid_attributes}, valid_session
        expect(assigns(:create_user_favorite)).to be_a_new(CreateUserFavorite)
      end

      it "re-renders the 'new' template" do
        post :create, {:create_user_favorite => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested create_user_favorite" do
        create_user_favorite = CreateUserFavorite.create! valid_attributes
        put :update, {:id => create_user_favorite.to_param, :create_user_favorite => new_attributes}, valid_session
        create_user_favorite.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested create_user_favorite as @create_user_favorite" do
        create_user_favorite = CreateUserFavorite.create! valid_attributes
        put :update, {:id => create_user_favorite.to_param, :create_user_favorite => valid_attributes}, valid_session
        expect(assigns(:create_user_favorite)).to eq(create_user_favorite)
      end

      it "redirects to the create_user_favorite" do
        create_user_favorite = CreateUserFavorite.create! valid_attributes
        put :update, {:id => create_user_favorite.to_param, :create_user_favorite => valid_attributes}, valid_session
        expect(response).to redirect_to(create_user_favorite)
      end
    end

    describe "with invalid params" do
      it "assigns the create_user_favorite as @create_user_favorite" do
        create_user_favorite = CreateUserFavorite.create! valid_attributes
        put :update, {:id => create_user_favorite.to_param, :create_user_favorite => invalid_attributes}, valid_session
        expect(assigns(:create_user_favorite)).to eq(create_user_favorite)
      end

      it "re-renders the 'edit' template" do
        create_user_favorite = CreateUserFavorite.create! valid_attributes
        put :update, {:id => create_user_favorite.to_param, :create_user_favorite => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested create_user_favorite" do
      create_user_favorite = CreateUserFavorite.create! valid_attributes
      expect {
        delete :destroy, {:id => create_user_favorite.to_param}, valid_session
      }.to change(CreateUserFavorite, :count).by(-1)
    end

    it "redirects to the create_user_favorites list" do
      create_user_favorite = CreateUserFavorite.create! valid_attributes
      delete :destroy, {:id => create_user_favorite.to_param}, valid_session
      expect(response).to redirect_to(create_user_favorites_url)
    end
  end

end
